#pragma once
//Generated By TheH3xRayz Offset Dumper 
/*** Public  ***/
const uintptr_t GW = 0x759f77c;
const uintptr_t GN = 0x785ee04;
const uintptr_t UWORLD = 4832052;
const uintptr_t GNAMES = 1950892;

/*** Player AActor ***/
const uintptr_t PlayerName = 0x648;
const uintptr_t Health = 0x93c;
const uintptr_t HealthMax = 0x940;
const uintptr_t TeamID = 0x670;
const uintptr_t Nation = 0x654;
const uintptr_t IsAi = 0x6e8;
//Vechiles shit
const uintptr_t VehicleCommon = 0x6a0;
const uintptr_t Fuel = 0x1cc;
const uintptr_t FuelMax = 0x1c8;
/*
=======TheH3xRayz#2005======
 Dump End Good Bye 
=======TheH3xRayz#2005======
*/

